apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: NodePort           # Change the service type to NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      nodePort: 31000      # Specify the desired nodePort
  selector:
    app: {{ .Release.Name }}-app
